
const fs = require("fs")

let electronics = [
    {
    img1: "https://images.meesho.com/images/products/60766541/bhiwm_512.jpg",
    Name: "AJOTICARE Back Cover For Oppo A83 (Dark Green)",
    price: "₹" + 120,
    Main_price: "₹" + 183,
    Discount: 30 + "%" + "off",
    p: "₹54 discount on 1st order",
    img2 : "https://images.meesho.com/images/products/60766541/b0jrg_512.jpg",
    img3: "https://images.meesho.com/images/products/60766541/jehxg_512.jpg",
    img4: "https://images.meesho.com/images/products/60766541/iomvp_512.jpg",
    delivery: "Free Delivery",
    Rating: 3.8,
    },
    {
        img1: "https://images.meesho.com/images/products/72994456/keb1j_512.jpg",
        Name: "Gs Covers Redmi K20",
        price: "₹" + 175,
        Main_price: "₹" + 249,
        Discount: 30 + "%" + "off",
        p: "₹74 discount on 1st order",
        img2 : null,
        img3: null,
        img4: null,
        delivery: "Free Delivery",
        Rating: 4.3,
        },
        {
            img1: "https://images.meesho.com/images/products/72981499/f3pm2_512.jpg",
            Name: "Gs Covers Redmi 9A",
            price: "₹" + 171,
            Main_price: "₹" +243,
            Discount: 30 + "%" + "off",
            p: "₹72 discount on 1st order",
            img2 : null,
            img3: null,
            img4: null,
            delivery: "Free Delivery",
            Rating:4.3,
            },
            {
                img1: "https://images.meesho.com/images/products/72973635/hofpf_512.jpg",
                Name: "PCM Printed Designer Matte finish Hard Back Cover for Samsung Galaxy J2 Pro 2018 / J2 2018 - 538",
                price: "₹" +122,
                Main_price: "₹" +173,
                Discount: 29 + "%" + "off",
                p: "₹51 discount on 1st order",
                img2 : null,
                img3: null,
                img4: null,
                delivery: "Free Delivery",
                Rating:3.8,
                },
 {
                    img1: "https://images.meesho.com/images/products/72973636/2ezo7_512.jpg",
                    Name: "PCM Printed Designer Matte finish Hard Back Cover for Samsung Galaxy J2 Pro 2018 / J2 2018 - 537",
                    price: "₹" +122,
                    Main_price: "₹" +173,
                    Discount: 29 + "%" + "off",
                    p: "₹51 discount on 1st order",
                    img2 : null,
                    img3: null,
                    img4: null,
                    delivery: "Free Delivery",
                    Rating:3.8,
                    },
                    {
                        img1: "https://images.meesho.com/images/products/51373374/ocjj8_512.jpg",
                        Name: "Itel A23 Pro Back Cover by Morenzoprint",
                        price: "₹" +126,
                        Main_price: "₹" +180,
                        Discount: 30 + "%" + "off",
                        p: "₹54 discount on 1st order",
                        img2 : "https://images.meesho.com/images/products/51373374/frkvz_512.jpg",
                        img3: "https://images.meesho.com/images/products/51373374/ahqpt_512.jpg",
                        img4: "https://images.meesho.com/images/products/51373374/9dp91_512.jpg",
                        delivery: "Free Delivery",
                        Rating:3.8,
                        },

                    {
                        img1: "https://images.meesho.com/images/products/71976122/muhyj_512.jpg",
                        Name: "The Holders Redmi Note 10 Pro Hard Case Back Cover",
                        price: "₹" +157,
                        Main_price: "₹" +223,
                        Discount: 30 + "%" + "off",
                        p: "₹66 discount on 1st order",
                        img2 :null ,
                        img3:null ,
                        img4: null,
                        delivery: "Free Delivery",
                        Rating:3.8,
                        },
                        {
                            img1: "https://images.meesho.com/images/products/72985569/srvos_512.jpg",
                            Name: "Gs Covers Redmi 9A",
                            price: "₹" +171,
                            Main_price: "₹" +243,
                            Discount: 30 + "%" + "off",
                            p: "₹72 discount on 1st order",
                            img2 :null ,
                            img3:null ,
                            img4: null,
                            delivery: "Free Delivery",
                            Rating:4.3,
                            },
                            {
                                img1: "https://images.meesho.com/images/products/72996733/httob_512.jpg",
                                Name: "Gs Covers Redmi K20",
                                price: "₹" +175,
                                Main_price: "₹" +249,
                                Discount: 30 + "%" + "off",
                                p: "₹74 discount on 1st order",
                                img2 :null ,
                                img3:null ,
                                img4: null,
                                delivery: "Free Delivery",
                                Rating:4.3,
                                },
                                {
                                    img1: "https://images.meesho.com/images/products/71976082/mi6bt_512.jpg",
                                    Name: "The Holders Redmi Note 10 Pro Hard Case Back Cover",
                                    price: "₹" +157,
                                    Main_price: "₹" +223,
                                    Discount: 30 + "%" + "off",
                                    p: "₹66 discount on 1st order",
                                    img2 :null ,
                                    img3:null ,
                                    img4: null,
                                    delivery: "Free Delivery",
                                    Rating:null,
                                    },
                                    {
                                        img1: "https://images.meesho.com/images/products/72475076/ib0at_512.jpg",
                                        Name: "Back Cover for Samsung Galaxy M42 5G",
                                        price: "₹" +192,
                                        Main_price: "₹" +273,
                                        Discount: 30 + "%" + "off",
                                        p: "₹81 discount on 1st order",
                                        img2 :null ,
                                        img3:null ,
                                        img4: null,
                                        delivery: "Free Delivery",
                                        Rating:null,
                                        },
                                        {
                                            img1: "https://images.meesho.com/images/products/71976030/aozpu_512.jpg",
                                            Name: "The Holders Redmi Note 10 Pro Hard Case Back Cover ",
                                            price: "₹" +157,
                                            Main_price: "₹" +223,
                                            Discount: 30 + "%" + "off",
                                            p: "₹66 discount on 1st order",
                                            img2 :null ,
                                            img3:null ,
                                            img4: null,
                                            delivery: "Free Delivery",
                                            Rating:null,
                                            },
                                            {
                                                img1: "https://images.meesho.com/images/products/72994456/keb1j_512.jpg",
                                                Name: "Gs Covers Redmi K20",
                                                price: "₹" +175,
                                                Main_price: "₹" +249,
                                                Discount: 30 + "%" + "off",
                                                p: "₹74 discount on 1st order",
                                                img2 :null ,
                                                img3:null ,
                                                img4: null,
                                                delivery: "Free Delivery",
                                                Rating:4.3,
                                                },
                                                {
                                                    img1: "https://images.meesho.com/images/products/51373377/j5qe7_512.jpg",
                                                    Name: "Itel A23 Pro Back Cover by Morenzoprint",
                                                    price: "₹" +126,
                                                    Main_price: "₹" +180,
                                                    Discount: 30 + "%" + "off",
                                                    p: "₹54 discount on 1st order",
                                                    img2 : "https://images.meesho.com/images/products/51373377/7hlbl_64.jpg",
                                                    img3: "https://images.meesho.com/images/products/51373377/ocjuy_64.jpg",
                                                    img4: "https://images.meesho.com/images/products/51373377/th4gy_64.jpg",
                                                    delivery: "Free Delivery",
                                                    Rating:3.8,
                                                    },
                                                    {
                                                        img1: "https://images.meesho.com/images/products/51373377/j5qe7_512.jpg",
                                                        Name: "Itel A23 Pro Back Cover by Morenzoprint",
                                                        price: "₹" +126,
                                                        Main_price: "₹" +180,
                                                        Discount: 30 + "%" + "off",
                                                        p: "₹54 discount on 1st order",
                                                        img2 : "https://images.meesho.com/images/products/51373374/frkvz_512.jpg",
                                                        img3: "https://images.meesho.com/images/products/51373374/ahqpt_512.jpg",
                                                        img4: "https://images.meesho.com/images/products/51373374/9dp91_512.jpg",
                                                        delivery: "Free Delivery",
                                                        Rating:3.8,
                                                        },
                                                        {
                                                            img1: "https://images.meesho.com/images/products/72922069/p0o2z_512.jpg",
                                                            Name: "T55 Series 5 Smart Watch Compatiable With All Smart Phones",
                                                            price: "₹" +168,
                                                            Main_price: "₹" +240,
                                                            Discount: 30 + "%" + "off",
                                                            p: "₹72 discount on 1st order",
                                                            img2 : null,
                                                            img3: null,
                                                            img4: null,
                                                            delivery: "Free Delivery",
                                                            Rating:null
                                                            },
                                                            {
                                                                img1: "https://images.meesho.com/images/products/72099695/ogpa3_512.jpg",
                                                                Name: "T55+ Series 6 Smart Watch With Bluetooth Calling /Health Fitness Tracker/ 2 Pin",
                                                                price: "₹" +1465,
                                                                Main_price: "₹" +1565,
                                                                Discount: 6 + "%" + "off",
                                                                p: "₹100 discount on 1st order",
                                                                img2 : null,
                                                                img3: null,
                                                                img4: null,
                                                                delivery: "Free Delivery",
                                                                Rating:3.5,
                                                                },
                                                                {
                                                                    img1: "https://images.meesho.com/images/products/71791807/xy2ex_512.jpg",
                                                                    Name: "A1C Sport Multifunction Dual Time Digital Chronograph Working Date Display Casual,Party Wear,Formal PU Strap Water&Shock Resistance Alarm Analog-Digital Watch - For Boys",
                                                                    price: "₹" +410,
                                                                    Main_price: "₹" +510,
                                                                    Discount: 20 + "%" + "off",
                                                                    p: "₹100 discount on 1st order",
                                                                    img2 : null,
                                                                    img3: null,
                                                                    img4: null,
                                                                    delivery: "Free Delivery",
                                                                    Rating:3.5,
                                                                    },
                                                                    {
                                                                        img1: "https://images.meesho.com/images/products/72991230/esgdg_512.jpg",
                                                                        Name: "GAMNIK.COM Mini Washing Machine, Portable Personal Rotary Ultrasonic Turbine Adjustable with USB Cable Convenient for Trav",
                                                                        price: "₹" +815,
                                                                        Main_price: "₹" +915,
                                                                        Discount: 11 + "%" + "off",
                                                                        p: "₹100 discount on 1st order",
                                                                        img2 : "https://images.meesho.com/images/products/72991230/hobah_512.jpg",
                                                                        img3: "https://images.meesho.com/images/products/72991230/78w9j_512.jpg",
                                                                        img4: "https://images.meesho.com/images/products/72991230/g5dow_512.jpg",
                                                                        delivery: "Free Delivery",
                                                                        Rating:3.6,
                                                                        },
                                                                        {
                                                                            img1: "https://images.meesho.com/images/products/72909853/judzf_512.jpg",
                                                                            Name: "Wooden Table /Desk Lamp Tripod Stand with Jute Shade and Home,Office Decorative Item",
                                                                            price: "₹" +1437,
                                                                            Main_price: "₹" +1537,
                                                                            Discount: 7 + "%" + "off",
                                                                            p: "₹100 discount on 1st order",
                                                                            img2 : "https://images.meesho.com/images/products/72909853/yihkj_512.jpg",
                                                                            img3: "https://images.meesho.com/images/products/72909853/mmviz_512.jpg",
                                                                            img4: null,
                                                                            delivery: "Free Delivery",
                                                                            Rating:3.6,
                                                                            },
                                                                            {
                                                                                img1: "https://images.meesho.com/images/products/72801130/vqi7j_512.jpg",
                                                                                Name: "Aqua Milano Flora with RO+ UV+ Pre-Filter+ Antiscalant+ Activated Carbon",
                                                                                price: "₹" +4350,
                                                                                Main_price: "₹" +4450,
                                                                                Discount: 2 + "%" + "off",
                                                                                p: "₹100 discount on 1st order",
                                                                                img2 : null,
                                                                                img3: null,
                                                                                img4: null,
                                                                                delivery: "Free Delivery",
                                                                                Rating: null
                                                                                },
                                                                                {
                                                                                    img1: "https://images.meesho.com/images/products/72801130/vqi7j_512.jpg",
                                                                                    Name: "Aqua Milano Flora with RO+ UV+ Pre-Filter+ Antiscalant+ Activated Carbon",
                                                                                    price: "₹" +4350,
                                                                                    Main_price: "₹" +4450,
                                                                                    Discount: 2 + "%" + "off",
                                                                                    p: "₹100 discount on 1st order",
                                                                                    img2 : null,
                                                                                    img3: null,
                                                                                    img4: null,
                                                                                    delivery: "Free Delivery",
                                                                                    Rating: null
                                                                                    }, 
                                                                                    {
                                                                                        img1: "https://images.meesho.com/images/products/72802359/uli1u_512.jpg",
                                                                                        Name: "Ottomate Smart Ceiling Fan Genus ( Pack of 1)",
                                                                                        price: "₹" +1810,
                                                                                        Main_price: "₹" +1910,
                                                                                        Discount: 5 + "%" + "off",
                                                                                        p: "₹100 discount on 1st order",
                                                                                        img2 : null,
                                                                                        img3: null,
                                                                                        img4: null,
                                                                                        delivery: "Free Delivery",
                                                                                        Rating: null
                                                                                        }, 
                                                                                        {
                                                                                            img1: "https://images.meesho.com/images/products/72995391/grp8m_512.jpg",
                                                                                            Name: "Fancy cool product",
                                                                                            price: "₹" +2389,
                                                                                            Main_price: "₹" +2489,
                                                                                            Discount:4 + "%" + "off",
                                                                                            p: "₹100 discount on 1st order",
                                                                                            img2 : null,
                                                                                            img3: null,
                                                                                            img4: null,
                                                                                            delivery: "Free Delivery",
                                                                                            Rating: null
                                                                                            }, 
                                                                                            {
                                                                                                img1: "https://images.meesho.com/images/products/72988689/vatnq_512.jpg",
                                                                                                Name: "Fancy cool product",
                                                                                                price: "₹" +1400,
                                                                                                Main_price: "₹" +1500,
                                                                                                Discount:7 + "%" + "off",
                                                                                                p: "₹100 discount on 1st order",
                                                                                                img2 : null,
                                                                                                img3: null,
                                                                                                img4: null,
                                                                                                delivery: "Free Delivery",
                                                                                                Rating: null
                                                                                                }, 
                                                                                                {
                                                                                                    img1: "https://images.meesho.com/images/products/72976357/evnsr_512.jpg",
                                                                                                    Name: "JETAL back cover for Oppo F19 Pro Plus",
                                                                                                    price: "₹" +143,
                                                                                                    Main_price: "₹" +203,
                                                                                                    Discount:30 + "%" + "off",
                                                                                                    p: "₹100 discount on 1st order",
                                                                                                    img2 : null,
                                                                                                    img3: null,
                                                                                                    img4: null,
                                                                                                    delivery: "Free Delivery",
                                                                                                    Rating: 3.6,
                                                                                                    },
                                                                                                    {
                                                                                                        img1: "https://images.meesho.com/images/products/72991411/mj6oy_512.jpg",
                                                                                                        Name: "Type C Fast Charging 1 m USB Type C Cable",
                                                                                                        price: "₹" +226,
                                                                                                        Main_price: "₹" +322,
                                                                                                        Discount:30 + "%" + "off",
                                                                                                        p: "₹96 discount on 1st order",
                                                                                                        img2 : null,
                                                                                                        img3: null,
                                                                                                        img4: null,
                                                                                                        delivery: "Free Delivery",
                                                                                                        Rating: 3.6,
                                                                                                        }, 
                                                                                                        {
                                                                                                            img1: "https://images.meesho.com/images/products/72989448/hbbea_512.jpg",
                                                                                                            Name: "Fancy cool product",
                                                                                                            price: "₹" +1899,
                                                                                                            Main_price: "₹" +1999,
                                                                                                            Discount:5 + "%" + "off",
                                                                                                            p: "₹100 discount on 1st order",
                                                                                                            img2 : null,
                                                                                                            img3: null,
                                                                                                            img4: null,
                                                                                                            delivery: "Free Delivery",
                                                                                                            Rating: null
                                                                                                            }, 
                                                                                                            {
                                                                                                                img1: "https://images.meesho.com/images/products/72993900/gimao_512.jpg",
                                                                                                                Name: "Gs Covers Redmi K20",
                                                                                                                price: "₹" +175,
                                                                                                                Main_price: "₹" +249,
                                                                                                                Discount:30+ "%" + "off",
                                                                                                                p: "₹74 discount on 1st order",
                                                                                                                img2 : null,
                                                                                                                img3: null,
                                                                                                                img4: null,
                                                                                                                delivery: "Free Delivery",
                                                                                                                Rating: 4.3,
                                                                                                                },
                                                                                                                {
                                                                                                                    img1: "https://images.meesho.com/images/products/72981668/pmsdn_512.jpg",
                                                                                                                    Name: "Gs Covers Redmi 9A",
                                                                                                                    price: "₹" +171,
                                                                                                                    Main_price: "₹" +243,
                                                                                                                    Discount:30+ "%" + "off",
                                                                                                                    p: "₹72 discount on 1st order",
                                                                                                                    img2 : null,
                                                                                                                    img3: null,
                                                                                                                    img4: null,
                                                                                                                    delivery: "Free Delivery",
                                                                                                                    Rating: 4.3,
                                                                                                                    },
                                                                                                                    {
                                                                                                                        img1: "https://images.meesho.com/images/products/72985589/6omoj_512.jpg",
                                                                                                                        Name: "Gs Covers Redmi 9A",
                                                                                                                        price: "₹" +171,
                                                                                                                        Main_price: "₹" +243,
                                                                                                                        Discount:30+ "%" + "off",
                                                                                                                        p: "₹72 discount on 1st order",
                                                                                                                        img2 : null,
                                                                                                                        img3: null,
                                                                                                                        img4: null,
                                                                                                                        delivery: "Free Delivery",
                                                                                                                        Rating: 4.3,
                                                                                                                        },
                                                                                                                        {
                                                                                                                            img1: "https://images.meesho.com/images/products/72475040/dxa7x_512.jpg",
                                                                                                                            Name: "Back Cover for Samsung Galaxy M42 5G",
                                                                                                                            price: "₹" +192,
                                                                                                                            Main_price: "₹" +273,
                                                                                                                            Discount:30+ "%" + "off",
                                                                                                                            p: "₹81 discount on 1st order",
                                                                                                                            img2 : null,
                                                                                                                            img3: null,
                                                                                                                            img4: null,
                                                                                                                            delivery: "Free Delivery",
                                                                                                                            Rating: null,
                                                                                                                            },
                                                                                                                            {
                                                                                                                                img1: "https://images.meesho.com/images/products/72464932/osczi_512.jpg",
                                                                                                                                Name: "MAHAKAL CREATION FOR BACK COVER OPPO A5s/A7",
                                                                                                                                price: "₹" +162,
                                                                                                                                Main_price: "₹" +231,
                                                                                                                                Discount: 30 + "%" + "off",
                                                                                                                                p: "₹69 discount on 1st order",
                                                                                                                                img2 : "https://images.meesho.com/images/products/72464932/onq6p_512.jpg",
                                                                                                                                img3: "https://images.meesho.com/images/products/72464932/rkbkx_512.jpg",
                                                                                                                                img4: null,
                                                                                                                                delivery: "Free Delivery",
                                                                                                                                Rating:4.1,
                                                                                                                                },
                                                                                                                                {
                                                                                                                                    img1: "https://images.meesho.com/images/products/72464935/cvxwk_512.jpg",
                                                                                                                                    Name: "MAHAKAL CREATION FOR BACK COVER OPPO A5s/A7",
                                                                                                                                    price: "₹" +162,
                                                                                                                                    Main_price: "₹" +231,
                                                                                                                                    Discount: 30 + "%" + "off",
                                                                                                                                    p: "₹69 discount on 1st order",
                                                                                                                                    img2 : "https://images.meesho.com/images/products/72464935/41wei_512.jpg",
                                                                                                                                    img3: "https://images.meesho.com/images/products/72464935/jmwi8_512.jpg",
                                                                                                                                    img4: null,
                                                                                                                                    delivery: "Free Delivery",
                                                                                                                                    Rating:4.1,
                                                                                                                                    },
                                                                                                                                    {
                                                                                                                                        img1: "https://images.meesho.com/images/products/72972144/ovbjl_512.jpg",
                                                                                                                                        Name: "NAV Printed Back Cover For Vivo Y91i / Vivo Y90 / Vivo Y1s Hard Plastic",
                                                                                                                                        price: "₹" +185,
                                                                                                                                        Main_price: "₹" +263,
                                                                                                                                        Discount: 30 + "%" + "off",
                                                                                                                                        p: "₹78 discount on 1st order",
                                                                                                                                        img2 : "https://images.meesho.com/images/products/72972144/cnl9v_512.jpg",
                                                                                                                                        img3: "https://images.meesho.com/images/products/72972144/uxoui_512.jpg",
                                                                                                                                        img4: "https://images.meesho.com/images/products/72972144/ye9kt_512.jpg",
                                                                                                                                        delivery: "Free Delivery",
                                                                                                                                        Rating:4.0,
                                                                                                                                        },
                                                                                                                                        {
                                                                                                                                            img1: "https://images.meesho.com/images/products/72981624/ehj0o_512.jpg",
                                                                                                                                            Name: "Gs Covers Redmi 9A",
                                                                                                                                            price: "₹" +171,
                                                                                                                                            Main_price: "₹" +243,
                                                                                                                                            Discount: 30 + "%" + "off",
                                                                                                                                            p: "₹72 discount on 1st order",
                                                                                                                                            img2 : null,
                                                                                                                                            img3: null,
                                                                                                                                            img4: null,
                                                                                                                                            delivery: "Free Delivery",
                                                                                                                                            Rating:4.1,
                                                                                                                                            },
                                                                                                                                            {
                                                                                                                                                img1: "https://images.meesho.com/images/products/72971282/znvzy_512.jpg",
                                                                                                                                                Name: "Realme 9i Back Cover",
                                                                                                                                                price: "₹" +122,
                                                                                                                                                Main_price: "₹" +173,
                                                                                                                                                Discount: 29 + "%" + "off",
                                                                                                                                                p: "₹51 discount on 1st order",
                                                                                                                                                img2 : null,
                                                                                                                                                img3: null,
                                                                                                                                                img4: null,
                                                                                                                                                delivery: "Free Delivery",
                                                                                                                                                Rating:3.8,
                                                                                                                                                },
                                                                                                                                                {
                                                                                                                                                    img1: "https://images.meesho.com/images/products/71976122/muhyj_512.jpg",
                                                                                                                                                    Name: "The Holders Redmi Note 10 Pro Hard Case Back Cover",
                                                                                                                                                    price: "₹" +157,
                                                                                                                                                    Main_price: "₹" +223,
                                                                                                                                                    Discount: 30 + "%" + "off",
                                                                                                                                                    p: "₹66 discount on 1st order",
                                                                                                                                                    img2 : null,
                                                                                                                                                    img3: null,
                                                                                                                                                    img4: null,
                                                                                                                                                    delivery: "Free Delivery",
                                                                                                                                                    Rating:null,
                                                                                                                                                    },
                                                                                                                                                    {
                                                                                                                                                        img1: "https://images.meesho.com/images/products/72993921/sac3o_512.jpg",
                                                                                                                                                        Name: "Gs Covers Redmi K20",
                                                                                                                                                        price: "₹" +175,
                                                                                                                                                        Main_price: "₹" + 249,
                                                                                                                                                        Discount: 29 + "%" + "off",
                                                                                                                                                        p: "₹74 discount on 1st order",
                                                                                                                                                        img2 : null,
                                                                                                                                                        img3: null,
                                                                                                                                                        img4: null,
                                                                                                                                                        delivery: "Free Delivery",
                                                                                                                                                        Rating:4.3,
                                                                                                                                                        },
                                                                                                                                                        {
                                                                                                                                                            img1: "https://images.meesho.com/images/products/72992598/p42oy_512.jpg",
                                                                                                                                                            Name: "Realme 9i Back Cover",
                                                                                                                                                            price: "₹" +122,
                                                                                                                                                            Main_price: "₹" + 173,
                                                                                                                                                            Discount: 29 + "%" + "off",
                                                                                                                                                            p: "₹51 discount on 1st order",
                                                                                                                                                            img2 : null,
                                                                                                                                                            img3: null,
                                                                                                                                                            img4: null,
                                                                                                                                                            delivery: "Free Delivery",
                                                                                                                                                            Rating:3.8,
                                                                                                                                                            },
                                                                                                                                                            {
                                                                                                                                                                img1: "https://images.meesho.com/images/products/72981443/s2iqr_512.jpg",
                                                                                                                                                                Name: "Gs Covers Redmi 9A",
                                                                                                                                                                price: "₹" +171,
                                                                                                                                                                Main_price: "₹" + 243,
                                                                                                                                                                Discount: 30 + "%" + "off",
                                                                                                                                                                p: "₹72 discount on 1st order",
                                                                                                                                                                img2 : null,
                                                                                                                                                                img3: null,
                                                                                                                                                                img4: null,
                                                                                                                                                                delivery: "Free Delivery",
                                                                                                                                                                Rating:4.3,
                                                                                                                                                                },
                                                                                                                                                                {
                                                                                                                                                                    img1: "https://images.meesho.com/images/products/72970901/wqb9u_512.jpg",
                                                                                                                                                                    Name: "NAV Printed Back Cover For Xiaomi Mi 11 Lite NE 5G / Mi 11 Lite / Hard Plastic Cases & Covers",
                                                                                                                                                                    price: "₹" +185,
                                                                                                                                                                    Main_price: "₹" + 263,
                                                                                                                                                                    Discount: 30 + "%" + "off",
                                                                                                                                                                    p: "₹78 discount on 1st order",
                                                                                                                                                                    img2 : null,
                                                                                                                                                                    img3: null,
                                                                                                                                                                    img4: null,
                                                                                                                                                                    delivery: "Free Delivery",
                                                                                                                                                                    Rating:4.0,
                                                                                                                                                                    },
                                                                                                                                                                    {
                                                                                                                                                                        img1: "https://images.meesho.com/images/products/72991287/h7ttx_512.jpg",
                                                                                                                                                                        Name: "Realme 9i Back Cover",
                                                                                                                                                                        price: "₹" +122,
                                                                                                                                                                        Main_price: "₹" + 173,
                                                                                                                                                                        Discount: 29 + "%" + "off",
                                                                                                                                                                        p: "₹51 discount on 1st order",
                                                                                                                                                                        img2 : null,
                                                                                                                                                                        img3: null,
                                                                                                                                                                        img4: null,
                                                                                                                                                                        delivery: "Free Delivery",
                                                                                                                                                                        Rating: 3.8,
                                                                                                                                                                        },
                                                                                                                                                                        {
                                                                                                                                                                            img1: "https://images.meesho.com/images/products/72464876/twbda_512.jpg",
                                                                                                                                                                            Name: "MAHAKAL CREATION FOR BACK COVER OPPO A5 2020/a9 2020",
                                                                                                                                                                            price: "₹" +162,
                                                                                                                                                                            Main_price: "₹" + 231,
                                                                                                                                                                            Discount: 30 + "%" + "off",
                                                                                                                                                                            p: "₹59 discount on 1st order",
                                                                                                                                                                            img2 : "https://images.meesho.com/images/products/72464876/mseo6_512.jpg",
                                                                                                                                                                            img3: "https://images.meesho.com/images/products/72464876/uo4yw_512.jpg",
                                                                                                                                                                            img4: null,
                                                                                                                                                                            delivery: "Free Delivery",
                                                                                                                                                                            Rating: 4.1,
                                                                                                                                                                            },
                                                                                                                                                                            {
                                                                                                                                                                                img1: "https://images.meesho.com/images/products/72997466/l31la_512.jpg",
                                                                                                                                                                                Name: "Gs Covers Redmi K20",
                                                                                                                                                                                price: "₹" +175,
                                                                                                                                                                                Main_price: "₹" + 249,
                                                                                                                                                                                Discount: 30 + "%" + "off",
                                                                                                                                                                                p: "₹74 discount on 1st order",
                                                                                                                                                                                img2 : null,
                                                                                                                                                                                img3: null,
                                                                                                                                                                                img4: null,
                                                                                                                                                                                delivery: "Free Delivery",
                                                                                                                                                                                Rating: 4.,
                                                                                                                                                                                },
                                                                                                                                                                                {
                                                                                                                                                                                    img1: "https://images.meesho.com/images/products/72973072/mz0cm_512.jpg",
                                                                                                                                                                                    Name: "PCM Printed Designer Matte finish Hard Back Cover for Samsung Galaxy J2 Pro 2018 / J2 2018 - 734",
                                                                                                                                                                                    price: "₹" +122,
                                                                                                                                                                                    Main_price: "₹" + 173,
                                                                                                                                                                                    Discount: 29+ "%" + "off",
                                                                                                                                                                                    p: "₹51 discount on 1st order",
                                                                                                                                                                                    img2 : null,
                                                                                                                                                                                    img3: null,
                                                                                                                                                                                    img4: null,
                                                                                                                                                                                    delivery: "Free Delivery",
                                                                                                                                                                                    Rating: 3.,
                                                                                                                                                                                    },
                                                                                                                                                                                    {
                                                                                                                                                                                        img1: "https://images.meesho.com/images/products/72993000/e4fms_512.jpg",
                                                                                                                                                                                        Name: "YASHTI Camera Protection Shutter Translucent Back Cover Case (Camera Bump Protector, Black and Blue ) For SAMSUNG A53",
                                                                                                                                                                                        price: "₹" +164,
                                                                                                                                                                                        Main_price: "₹" + 233,
                                                                                                                                                                                        Discount: 30 + "%" + "off",
                                                                                                                                                                                        p: "₹ 69 discount on 1st order",
                                                                                                                                                                                        img2 : "https://images.meesho.com/images/products/72993000/pes6x_64.jpg",
                                                                                                                                                                                        img3: "https://images.meesho.com/images/products/72993000/42oo6_512.jpg",
                                                                                                                                                                                        img4: "https://images.meesho.com/images/products/72993000/fmw9l_512.jpg",
                                                                                                                                                                                        delivery: "Free Delivery",
                                                                                                                                                                                        Rating: 3.1,
                                                                                                                                                                                        },
                                                                                                                                                                                        {
                                                                                                                                                                                            img1: "https://images.meesho.com/images/products/72973421/ivd4f_512.jpg",
                                                                                                                                                                                            Name: "PCM Printed Designer Matte finish Hard Back Cover for Samsung Galaxy J2 Pro 2018 / J2 2018 - 245",
                                                                                                                                                                                            price: "₹" +122,
                                                                                                                                                                                            Main_price: "₹" + 173,
                                                                                                                                                                                            Discount: 29+ "%" + "off",
                                                                                                                                                                                            p: "₹ 51 discount on 1st order",
                                                                                                                                                                                            img2 :null,
                                                                                                                                                                                            img3: null,
                                                                                                                                                                                            img4: null,
                                                                                                                                                                                            delivery: "Free Delivery",
                                                                                                                                                                                            Rating: 3.8,
                                                                                                                                                                                            },
                                                                                                                                                                                            {
                                                                                                                                                                                                img1: "https://images.meesho.com/images/products/72981900/bnoft_512.jpg",
                                                                                                                                                                                                Name: "Gs Covers Redmi 9A",
                                                                                                                                                                                                price: "₹" +171,
                                                                                                                                                                                                Main_price: "₹" + 243,
                                                                                                                                                                                                Discount: 30 + "%" + "off",
                                                                                                                                                                                                p: "₹ 72 discount on 1st order",
                                                                                                                                                                                                img2 :null,
                                                                                                                                                                                                img3: null,
                                                                                                                                                                                                img4: null,
                                                                                                                                                                                                delivery: "Free Delivery",
                                                                                                                                                                                                Rating: 4.3,
                                                                                                                                                                                                },
                                                                                                                                                                                                {
                                                                                                                                                                                                    img1: "https://images.meesho.com/images/products/71975970/pjusl_512.jpg",
                                                                                                                                                                                                    Name: "The Holders Redmi Note 10 Pro Hard Case Back Cover",  
                                                                                                                                                                                                    price: "₹" +157,
                                                                                                                                                                                                    Main_price: "₹" + 223,
                                                                                                                                                                                                    Discount: 30 + "%" + "off",
                                                                                                                                                                                                    p: "₹ 66 discount on 1st order",
                                                                                                                                                                                                    img2 :null,
                                                                                                                                                                                                    img3: null,
                                                                                                                                                                                                    img4: null,
                                                                                                                                                                                                    delivery: "Free Delivery",
                                                                                                                                                                                                    Rating: null,
                                                                                                                                                                                                    },
                                                                                                                                                                                                    {
                                                                                                                                                                                                        img1: "https://images.meesho.com/images/products/72984770/g4hyt_512.jpg",
                                                                                                                                                                                                        Name: "Gs Covers Redmi 9A",  
                                                                                                                                                                                                        price: "₹" +171,
                                                                                                                                                                                                        Main_price: "₹" + 243,
                                                                                                                                                                                                        Discount: 30 + "%" + "off",
                                                                                                                                                                                                        p: "₹ 72 discount on 1st order",
                                                                                                                                                                                                        img2 :null,
                                                                                                                                                                                                        img3: null,
                                                                                                                                                                                                        img4: null,
                                                                                                                                                                                                        delivery: "Free Delivery",
                                                                                                                                                                                                        Rating: 4.3,
                                                                                                            
                                                                                                                                                                                                    }
    


                                        
                                                                                                                                                                                
                                                                                                                                                                                                ]
                                                                                                                                                                                                const jsonData = JSON.stringify(electronics);
                                                                                                                                                                                                fs.writeFile("electronic.json", jsonData,(err) =>{
                                                                                                                                                                                                console.log("done");
                                                                                                                                                                                                })                                                                                                                                                                                               